kind: Deployment
apiVersion: apps/v1
metadata:
  name: go-with-gin-deployment
  namespace: go-wth-gin-app
  labels:
    app: go-with-gin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-with-gin-deployment
  template:
    metadata:
      labels:
        app: go-with-gin-deployment
    spec:
      containers:
        - name: go-with-gin-deployment
          image: acrfortests.azurecr.io/go-wth-gin-app:latest
          ports:
            - containerPort: 80
              protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: go-with-gin-deployment
  namespace: go-wth-gin-app
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: go-with-gin-deployment