name: Trigger auto deployment for go-wth-gin-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/go-wth-gin-app-AutoDeployTrigger-9f6d8b9c-59d2-4e26-a992-016b1225dbbd.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.GOWTHGINAPP_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: acrfortests.azurecr.io
          registryUsername: ${{ secrets.GOWTHGINAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.GOWTHGINAPP_REGISTRY_PASSWORD }}
          containerAppName: go-wth-gin-app
          resourceGroup: RG_GO_DOCKER_TESTS
          imageToBuild: acrfortests.azurecr.io/go-wth-gin-app:${{ github.sha }}
          dockerfilePath: Dockerfile

     

