on: [push]
name: Go_to_ACR

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - uses: azure/docker-login@v1
          with:
            login-server: acrfortests.azurecr.io
            username: ${{ secrets.GIT_TO_ACR_USER }}
            password: ${{ secrets.GIT_TO_ACR_PASS }}
        - run: |
            docker build . -t acrfortests.azurecr.io/go-wth-gin-app
            docker push acrfortests.azurecr.io/go-wth-gin-app:latest

        - name: 'Deploy to Azure Container Instances'
          uses: 'azure/aci-deploy@v1'
          with:
            resource-group: RG_GO_DOCKER_TESTS
            dns-name-label: go-wth-gin
            image: acrfortests.azurecr.io/go-wth-gin-app:latest
            registry-login-server: acrfortests.azurecr.io
            registry-username: ${{ secrets.GIT_TO_ACR_USER }}
            registry-password: ${{ secrets.GIT_TO_ACR_PASS }}
            name: go-wth-gin
            location: east us 2
            memory: 1
            restart-policy: OnFailure

        - name: Deploy to Container App
          uses: azure/container-apps-deploy-action@v1
          with:
            appSourcePath: ${{ github.workspace }}/src
            acrName: acrfortests
            containerAppName: go-wth-gin-app
            resourceGroup: RG_GO_DOCKER_TESTS
