on: [push]
name: Go_to_ACR

jobs:
    build-and-push-image:
        name: Build and Push Docker Image
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - uses: azure/docker-login@v1
          with:
            login-server: acrfortests.azurecr.io
            username: ${{ secrets.GIT_TO_ACR_USER }}
            password: ${{ secrets.GIT_TO_ACR_PASS }}
        - run: |
            docker build . -t acrfortests.azurecr.io/go-wth-gin-app:${{ github.sha }}
            docker push acrfortests.azurecr.io/go-wth-gin-app:${{ github.sha }}
    deploy-to-aci:
      name: Deploy to Azure Container Instances
      runs-on: ubuntu-latest
      needs: build-and-push-image
      steps:
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        - name: 'Deploy to Azure Container Instances'
          uses: 'azure/aci-deploy@v1'
          with:
            resource-group: RG_GO_DOCKER_TESTS
            dns-name-label: go-wth-gin
            image: acrfortests.azurecr.io/go-wth-gin-app:${{ github.sha }}
            registry-login-server: acrfortests.azurecr.io
            registry-username: ${{ secrets.GIT_TO_ACR_USER }}
            registry-password: ${{ secrets.GIT_TO_ACR_PASS }}
            name: go-wth-gin
            location: east us 2
            memory: 1
            restart-policy: OnFailure
    deploy-to-aca:
      name: Deploy to Azure Container Apps
      runs-on: ubuntu-latest
      needs: build-and-push-image
      steps:
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        - name: Deploy to Container App
          uses: azure/container-apps-deploy-action@v1
          with:
            acrName: acrfortests
            containerAppName: go-wth-gin-app
            resourceGroup: RG_GO_DOCKER_TESTS
            imageToDeploy: acrfortests.azurecr.io/go-wth-gin-app:${{ github.sha }}

    deploy-to-aks:
      name: Deploy to Azure Kubernetes Service
      runs-on: ubuntu-latest
      needs: build-and-push-image
      steps:
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master
        - name: Setup kubectl
          uses: azure/setup-kubectl@v3
        - name: Set AKS context
          uses: azure/aks-set-context@v1
          with:
            creds: '${{ secrets.AZURE_CREDENTIALS }}'
            resource-group: 'RG_GO_DOCKER_TESTS' 
            cluster-name: 'aks-cluster-for-gin'
        - name: Create Secret
          uses: Azure/k8s-create-secret@v1.1
          with:
              container-registry-url: acrfortests.azurecr.io
              container-registry-username: ${{ secrets.GIT_TO_ACR_USER }}
              container-registry-password: ${{ secrets.GIT_TO_ACR_PASS }}
              secret-name: demo-k8s-secret
        - name: Deploy to AKS
          uses: Azure/k8s-deploy@v4
          with:
            action: deploy
            namespace: 'go-wth-gin-app'
            manifests: |
              deploy-aks.yml
            images: acrfortests.azurecr.io/go-wth-gin-app:${{ github.sha }}
            imagepullsecrets: |
                 demo-k8s-secret